# This is the name that will be visible in the runned Pipeline
#name: '$(BuildDefinitionName)_Id$(Build.BuildId)_$(SourceBranchName)_$(Date:yyyyMMdd)'
trigger:
    none

pr:
    none

pool:
  # The agent should be ubuntu, 
  vmImage: 'ubuntu-latest'

stages:
    - stage: PersonsCI
      displayName: Persons CI Stage
      jobs:
        - job:
          displayName: Persons build and push job
          steps:
            - task: DockerCompose@1
              displayName: Persons build task
              inputs:
                containerregistrytype: 'Azure Container Registry'
                azureSubscription: 'Azure subscription Pay as you go(6b707fea-0a44-4ee3-8c61-f2c29d7a2d25)'
                azureContainerRegistry: '{"loginServer":"bhcontainerregistry.azurecr.io", "id" : "/subscriptions/6b707fea-0a44-4ee3-8c61-f2c29d7a2d25/resourceGroups/BHbigdata/providers/Microsoft.ContainerRegistry/registries/BHcontainerregistry"}'
                dockerComposeFile: 'docker/docker-compose.yml'
                action: 'Build services'
                includeLatestTag: true
              
            - task: DockerCompose@1
              displayName: Persons push task
              inputs:
                containerregistrytype: 'Azure Container Registry'
                azureSubscription: 'Azure subscription Pay as you go(6b707fea-0a44-4ee3-8c61-f2c29d7a2d25)'
                azureContainerRegistry: '{"loginServer":"bhcontainerregistry.azurecr.io", "id" : "/subscriptions/6b707fea-0a44-4ee3-8c61-f2c29d7a2d25/resourceGroups/BHbigdata/providers/Microsoft.ContainerRegistry/registries/BHcontainerregistry"}'
                dockerComposeFile: 'docker/docker-compose.yml'
                action: 'Push services'
                includeLatestTag: true
             
                
    - stage: PersonsCD
      displayName: Persons CD stage
      dependsOn: PersonsCI
      jobs:
        - job: PersonsDeploy
          displayName: Persons Deploy job
          steps:
            - task: AzureContainerApps@1
              displayName: Hello-service deploy task
              inputs:
                azureSubscription: 'Azure subscription Pay as you go(6b707fea-0a44-4ee3-8c61-f2c29d7a2d25)'
                acrName: 'bhcontainerregistry'
                acrUsername: 'bhcontainerregistry'
                acrPassword: 'bxys+3nkh/eC7ounXuUkoCMkYAFFZNSiOTTy5+quC0+ACRDEj4DS'
                imageToDeploy: 'bhcontainerregistry.azurecr.io/Persons/hello-service'
                containerAppName: 'hello-service'
                resourceGroup: 'bhbigdata'
                containerAppEnvironment: 'bigdata-env'
                targetPort: '80'
                location: 'northeurope'
                environmentVariables: 'HELLO_SERVICE_PORT=80'
                ingress: 'internal'
                disableTelemetry: true
              
            - task: AzureContainerApps@1
              displayName: World-service deploy task
              inputs:
                azureSubscription: 'Azure subscription Pay as you go(6b707fea-0a44-4ee3-8c61-f2c29d7a2d25)'
                acrName: 'bhcontainerregistry'
                acrUsername: 'bhcontainerregistry'
                acrPassword: 'bxys+3nkh/eC7ounXuUkoCMkYAFFZNSiOTTy5+quC0+ACRDEj4DS'
                imageToDeploy: 'bhcontainerregistry.azurecr.io/Persons/world-service'
                containerAppName: 'world-service'
                resourceGroup: 'bhbigdata'
                containerAppEnvironment: 'bigdata-env'
                targetPort: '80'
                location: 'northeurope'
                environmentVariables: 'WORLD_SERVICE_PORT=80'
                ingress: 'internal'
                disableTelemetry: true
              
            
            - task: AzureContainerApps@1
              displayName: Greetings-service deploy task
              inputs:
                azureSubscription: 'Azure subscription Pay as you go(6b707fea-0a44-4ee3-8c61-f2c29d7a2d25)'
                acrName: 'bhcontainerregistry'
                acrUsername: 'bhcontainerregistry'
                acrPassword: 'bxys+3nkh/eC7ounXuUkoCMkYAFFZNSiOTTy5+quC0+ACRDEj4DS'
                imageToDeploy: 'bhcontainerregistry.azurecr.io/Persons/greetings-service'
                containerAppName: 'greetings-service'
                resourceGroup: 'bhbigdata'
                containerAppEnvironment: 'bigdata-env'
                targetPort: '80'
                location: 'northeurope'
                environmentVariables: 'PORT=80 HELLO_SERVICE_HOST_PREFIX=http://hello-service WORLD_SERVICE_HOST_PREFIX=http://world-service'
                ingress: 'external'
                disableTelemetry: true
              
            
            
          


